### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by DiamondBond** [HybridMod/Current#13]
Not a major issue, but what OS's are you guys running? @hoholee12 @DeicPro , i think its an issue on my side but the time is so messed up with git and github, when i commit it says i committed yesterday, i reset my hwclock and synced it with my local time and i think its fine now, but if it continues just leave a note here, cause its annoying to get all commits messed up...

**Comment by DeicPro** [comment]
yes i saw and i thought am in the drug or something lol

**Comment by DiamondBond** [comment]
@DeicPro xD

**Comment by DeicPro** [comment]
do a test to try if is fix

**Comment by DiamondBond** [comment]
@DeicPro lol no its not fixed, commited now, look:
"5 hours ago timezone test"

**Comment by DeicPro** [comment]
@DiamondBond I see 3 min ago lol...

**Comment by DiamondBond** [comment]
@DeicPro ehh its fine then, as long as git lists the commits in the right order im happy :)

**Comment by DeicPro** [comment]
yeah, 20 hours ago was like witchcraft xD

**Comment by hoholee12** [comment]
i think this is an obvious problem since we are all separated on very faraway timezones.
i too have experienced that on xda website few years back.

**Comment by DeicPro** [comment]
but that only appears if you push from local clone repo yep? I use the webpage to push commits xD
