### ISSUE TITLE
Resolution Quick Switch - Res QS

### ISSUE THREAD

**Issue by DiamondBond** [HybridMod/Current#15]
resolution changing :D this is good for gamers.

```
wm size 1080x1920   #the display resoltuion here, you can upscale aswell, no problem, the display will just be weird
                    #also android resolution = flipped, just remember that.
wm density 469      #density, must be adequately changed with the resolution.

wm size reset       #reset commands
wm density reset    #again reset command here
```

 So yeah , wanna implement this in our script, take a look at our legacy repo, theres a script called jeeves in there, it already
 does this but the implementation isnt so great i guess...
 linkys: https://github.com/HybridMod/Legacy/blob/master/jeeves.sh

**Comment by DeicPro** [comment]
I know as works, I saw jeeves code when edited your rtrm script xD

**Comment by DiamondBond** [comment]
@DeicPro it works, but we need to have a nice implementation of it :3

**Comment by DeicPro** [comment]
@DiamondBond 
Im thinking a method:
in game booster menu, an option called games that shows all package name apps & the user type the package name of his games & they are saved in a list, in other menu the user can run a game that he saved in the list of games & and when detect that process/package is closed, game booster is off and revert the game boost

only i have that think as do it xD

**Comment by DiamondBond** [comment]
@DeicPro i didnt understand xD
I like your idea to add "Resolution Quick Switch" as one of the options in the Game Booster menu. :)

edit
only issue with the resolution switcher is that it wont work for every device since not every device has the same resolution so we would need alot of different entries / checks. I think we should reserve this function for hybrid mod 2.6 or above, for now i want to get a stable version of HybridMod made, that will be v2.5 :D so we need to solve all the little issues and get it working 100% or improve code more, but no new features for now.

**Comment by DiamondBond** [comment]
mind changed, this feature will be reserved for v2.6 or above, projects aim is to get a stable release out as version 2.5. :)

**Comment by DeicPro** [comment]
@DiamondBond
Retard mode: on

game_booster() > game_list() > echo "com.example" > wm size/density && drop_caches > com.example is closed > wm size/density reset > Success :]

edit-

Retard mode: off

Okok m8

**Comment by DiamondBond** [comment]
xD @DeicPro now i understand, so throw the if in a loop, if app = open then resize, good, but it gets buggy and weird, try out the re-sizing commands in a terminal, if you reset the size and reboot everything will be fine, so keep this for 2.6+ , for now lets improve code / fix code xD and make the script presentable to the users and then publish it!

**Comment by DeicPro** [comment]
Android UI obviously but the game is the same reboot or not, so isn't relevant.
