### ISSUE TITLE
stat -c

### ISSUE THREAD

**Issue by DiamondBond** [HybridMod/Current#16]
upon executing hybrid.sh as root the script outputs verbose messages, this is not user friendly and should be hidden unless $debug = 1

![Example](http://i.imgur.com/vOgjVan.png)

**Comment by hoholee12** [comment]
will look into it.:)

meanwhile, you should directly run the script with ./ instead of sh for the api to work. executing interpreter and passing the location as an argument will not give any sort of clues to the api.

**Comment by DiamondBond** [comment]
@hoholee12 right, ill execute via ./ next time (via a shell instead of crappy smanager)
