### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by DiamondBond** [HybridMod/Current#21]
![alt tag](http://i.imgur.com/vTckom4.png)
Syntax highlighting is messed up (this is not a sublime issue, this is an issue somewhere in the script in this function, i just cant seem to find out where...)
$EDITOR=Sublime Text 3 Dev

**Comment by DeicPro** [comment]
line 1060: echo "This`<---

**Comment by hoholee12** [comment]
that is why i never even touch that key. its also known to be not recommended by many.

**Comment by DiamondBond** [comment]
@hoholee12 i thought it might be that, it escapes alot of stuff :/ @DeicPro i accidentally did that lol will fix now
