### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DiamondBond** [HybridMod/Current#22]
upon running the script via:

```
sh hybrid.sh
```

it returns wc errors and that it cant find the location

and trying to run via ./ will result in permission errors, we need to clean this up since not everyone can reformat there partitions and stuff just to exec a script xD

also another issue preventing the script from leading into execution is a fi (a045d2e)

**Comment by hoholee12** [comment]
im still looking at the fi error, just wait

**Comment by DiamondBond** [comment]
@hoholee12 okai

**Comment by hoholee12** [comment]
all fixed!

**Comment by DiamondBond** [comment]
:) never thought semi colons were that needed... lol thanks!
