### ISSUE TITLE
theres one problem to fix....

### ISSUE THREAD

**Issue by hoholee12** [HybridMod/Current#25]
@DiamondBond @DeicPro there is something we have to fix, were not done yet...
when i run the script, it goes in install_options, falls back to title and then back to install_options etc etc
its a loop.
we should do something about this, the only way i can access the body and other counterparts is through --debug menu.

btw, @DiamondBond those ram tweaks are awesome:D

**Comment by DeicPro** [comment]
Because persist.hybrid.permanent value doesn't update until re-run the script... Changing this to a config file & write that settings here & read with grep, is fix

**Comment by DiamondBond** [comment]
Guys my old laptop got rekt, so im MIA until my new one comes along... (latest arrival time: Monday) ;-; (using github in aosp browser is a PITA.)

As @DeicPro suggested we should convert the inscript variable to an external file based variable.

also thanks @hoholee12 , no one usually appreciates them xD i spent like a whole month in the summer of 2014 literally trying out random variables and looking at stats and reading tonnes of online articles about vm and oom and etc and finally settled at a bunch of values that suit different conditions (after much debugging and testing lol), i personally use the multitasking lmk + tuned vm values :3

**Comment by DeicPro** [comment]
@DiamondBond I put shit from phone always I hate mother fker sitin in a chair to use mother fker desktop xD, my mother fker shitty hp laptop died a lot of months ago :(...

Dat permanent value can apply of some ways:
1. simply grep the value of /data/property/persist.hyb...
2. create a config file in other loc & put variables on it & grep
3. create a file & check his name like:
If file name is perm.0, is temporally
If perm.1, permanent...

Which you like it...

**Comment by DiamondBond** [comment]
@DeicPro lol
how about cat /data/hybridstat
and if the output = 1 then permanent and if 0 then temp... :)

**Comment by DeicPro** [comment]
@DiamondBond yeah dat waste less resources lol

**Comment by DeicPro** [comment]
fixed d8567211d7c8a3f12618b01587794a7634e74793
